config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


resources :blogs

get 'about', to: 'blogs#about_change'

root 'blogs#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController


 before_action :find_id, only: [:show, :update, :destroy, :edit]

def index
  # set a variable to all Blogs inside the database.
  @Blogs = Blog.all
 end

 def show
 end

 def new
   @blog = Blog.new
end

def create

  @blog = Blog.create(define_params)

  if @blog.save
    redirect_to root_path
  else
    render :new
end
end

def edit


end

def update
 if @blog.update(define_params)
   redirect_to root_path
 else
   render :edit
 end
end

def destroy
@blog.destroy

  redirect_to root_path
end

private

def find_id
  @blog = Blog.find(params[:id])
end

def define_params
  params.require(:blog).permit(:title, :content)

end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
  <%= form_with model: @blog, local: true do |b| %>

  <%= b.text_field :title, class: 'form-control', placeholder: 'Title' %>
  <br>
  <%= b.text_area :content, class: 'form-control', placeholder: 'content' %>

  <%= b.submit %>



  <% end %>

app/views/blogs/about.html.erb
<div class="container">

<div class="row">

  <div class="col-md-6 offset-3 text-center">
    <div class="about_page">
<h3>About this application</h3>
<p>This application is made by a tutorial on youtube that explains
the core mechanics in Rails.</p>
</div>

</div>

</div>
</div>

app/views/blogs/edit.html.erb
<div class="container" id="form_container">


<h3>Edit post</h3>
<hr>



<%= render 'form' %>
</div>

app/views/blogs/index.html.erb
<div class="container">
<div class="row">





<% @Blogs.each do |b| %>
  <div class="col-md-4" id="card_margin">
<div class="card" style="width: 18rem">
  <div class="card-body">
    <h5 class="card-title">
      <%= b.title %>

    </h5>
    <p class-"card-text">
      <%= b.content %>
      </p>
      <%= link_to "View", blog_path(b), class: 'btn btn-outline-primary' %>
      <%= link_to "Edit", edit_blog_path(b), class: 'btn btn-outline-primary' %>
      <%= link_to "Delete", blog_path(b), class: 'btn btn-outline-danger', method: :delete, data: { confirm: 'Are you sure?'} %>

  </div>
</div>



</div>
<% end %>

</div>
</div>

app/views/blogs/new.html.erb
<div class="container" id="form_container">




<h1>Add a Blog post</h1>
<hr>
<%= render 'form' %>
</div>

app/views/blogs/show.html.erb
<div class="container" id="show_page">

</div>


<h1><%= @blog.title %></h1>
<hr>
<br>
<p><%= @blog.content %></p>


<%= link_to "Back", root_path, class: 'btn btn-outline-primary' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'shared/nav' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_nav.html.erb
<div class="container">

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">BlogApp</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-mr-auto">
      <li class="nav-item">
        <%= link_to "About", about_path, class: 'nav-link' %>

      </li>
      <li class="nav-item">

        <%= link_to "Blog", blogs_path, class: 'nav-link' %>
      </li>

<li class="nav-item activa">
       <%= link_to "New Post", new_blog_path, class: 'nav-link' %>

    </ul>

  </div>
</nav>
</div>